-- De Tre Alkoholikere — compact seed
insert into categories (id,name,emoji,sort_order,attribute_schema) values
  ('beer',$q$Beer$q$,$q$🍺$q$,1,$q$[{"key": "style", "label": "Style", "type": "text"}, {"key": "color", "label": "Color", "type": "text"}]$q$::jsonb),
  ('vermouth',$q$Vermouth$q$,$q$🍸$q$,2,$q$[{"key": "style", "label": "Style", "type": "select", "options": ["Rosso", "Bianco", "Dry", "Amber", "Rosé"]}, {"key": "region", "label": "Region", "type": "text"}]$q$::jsonb),
  ('wine',$q$Wine$q$,$q$🍷$q$,3,$q$[{"key": "color", "label": "Color", "type": "select", "options": ["Red", "White", "Rosé", "Orange"]}, {"key": "grape", "label": "Grape", "type": "text"}, {"key": "region", "label": "Region", "type": "text"}, {"key": "vintage", "label": "Vintage", "type": "number"}]$q$::jsonb),
  ('sparkling',$q$Sparkling$q$,$q$🥂$q$,4,$q$[{"key": "style", "label": "Type", "type": "select", "options": ["Champagne", "Cava", "Prosecco", "Crémant", "Other"]}, {"key": "region", "label": "Region", "type": "text"}, {"key": "vintage", "label": "Vintage", "type": "number"}]$q$::jsonb),
  ('rum',$q$Rum$q$,$q$🥃$q$,5,$q$[{"key": "region", "label": "Region", "type": "text"}, {"key": "age", "label": "Age (years)", "type": "number"}]$q$::jsonb),
  ('whiskey',$q$Whiskey$q$,$q$🥃$q$,6,$q$[{"key": "style", "label": "Type", "type": "select", "options": ["Single Malt", "Bourbon", "Rye", "Blended", "Other"]}, {"key": "region", "label": "Region", "type": "text"}, {"key": "age", "label": "Age (years)", "type": "number"}]$q$::jsonb),
  ('gin',$q$Gin$q$,$q$🍸$q$,7,$q$[{"key": "style", "label": "Style", "type": "select", "options": ["London Dry", "Old Tom", "Navy", "Contemporary", "Other"]}, {"key": "botanicals", "label": "Botanicals", "type": "text"}]$q$::jsonb)
on conflict (id) do nothing;

insert into tasters (name,sort_order) values ('Emil',1),('Frederik',2),('Søren',3) on conflict (name) do nothing;

insert into sessions (category_id,name) values
  ('beer',$q$Aften hos Frederik$q$),
  ('beer',$q$Hillerød$q$),
  ('beer',$q$Julefrokost hos Emil$q$),
  ('beer',$q$Ukendt aften (historisk)$q$);

insert into products (category_id,name,producer,abv,attributes) values
  ('beer',$q$Guldøl (Passion)$q$,$q$Tuborg$q$,5.6,$q${"style": "Guldøl", "color": "Lys"}$q$::jsonb),
  ('beer',$q$Jule-hvidtøl$q$,$q$Ceres$q$,1.9,$q${"style": "Hvidtøl", "color": "Mørk"}$q$::jsonb),
  ('beer',$q$Blonde$q$,$q$La Goudale$q$,7.2,$q${"style": "Hvedeøl", "color": "Pilsner"}$q$::jsonb),
  ('beer',$q$Brown ale$q$,$q$Newcastle$q$,4.7,$q${"style": "Brown ale", "color": "Karamel brun"}$q$::jsonb),
  ('beer',$q$Øko Classic$q$,$q$Gram Slot$q$,4.8,$q${"style": "Pilsner", "color": "Pilsner"}$q$::jsonb),
  ('beer',$q$Brown$q$,$q$Thisted Bryghus$q$,6.5,$q${"style": "Brown ale", "color": "Te"}$q$::jsonb),
  ('beer',$q$Velvet Galaxy$q$,$q$Jacobsen$q$,6.9,$q${"style": "Hvedeøl", "color": "Honning"}$q$::jsonb),
  ('beer',$q$Limfjords Porter$q$,$q$Thisted Bryghus$q$,8.4,$q${"style": "Porter", "color": "Kul"}$q$::jsonb),
  ('beer',$q$Glutenfri Øko Julebryg$q$,$q$Svaneke$q$,5.7,$q${"style": "Juleøl", "color": "Kaffe"}$q$::jsonb),
  ('beer',$q$Czech Lager$q$,$q$Budějovický Budvar$q$,4.6,$q${"style": "Pilsner", "color": "Gylden"}$q$::jsonb),
  ('beer',$q$Blå Thor$q$,$q$Thor$q$,6.0,$q${"style": "Pilsner", "color": "Gul"}$q$::jsonb),
  ('beer',$q$Weissbier$q$,$q$Paulaner München$q$,5.5,$q${"style": "Hvedeøl", "color": "Mat Pis"}$q$::jsonb),
  ('beer',$q$HC Andersen$q$,$q$Albani$q$,9.0,$q${"style": "Pilsner", "color": "Honning"}$q$::jsonb),
  ('beer',$q$Double Ambrée$q$,$q$Grimbergen$q$,6.5,$q${"style": "Brown ale", "color": "Rav"}$q$::jsonb),
  ('beer',$q$St. Omer$q$,$q$Brasserie Francaise$q$,8.0,$q${"style": "Blond ale", "color": "Død pilsner"}$q$::jsonb),
  ('beer',$q$Biére Blonde Légére$q$,$q$Goudale$q$,5.2,$q${"style": "Lager", "color": "Ufiltreret"}$q$::jsonb),
  ('beer',$q$Imperial Stout$q$,$q$Stem Brew$q$,7.5,$q${"style": "Stout", "color": "Sort"}$q$::jsonb),
  ('beer',$q$Top pilsner$q$,$q$Ceres$q$,4.6,$q${"style": "Pilsner", "color": "Pilsner"}$q$::jsonb),
  ('beer',$q$Didrik$q$,$q$De 5 gaarde$q$,7.5,$q${"style": "Pale ale", "color": "Klassisk"}$q$::jsonb),
  ('beer',$q$?$q$,$q$?$q$,5.2,$q${"style": "Hvedeøl", "color": "Mat lys"}$q$::jsonb),
  ('beer',$q$Ufiltreret mango IPA$q$,$q$Schiøtz$q$,5.5,$q${"style": "IPA", "color": "Ufiltreret"}$q$::jsonb),
  ('beer',$q$Dunkel$q$,$q$Erdinger$q$,5.3,$q${"style": "Hvedeøl", "color": "Sort"}$q$::jsonb),
  ('beer',$q$GB Jul$q$,$q$Gourmet Bryggeriet$q$,8.0,$q${"style": "Juleøl", "color": "Cola"}$q$::jsonb),
  ('beer',$q$Blanche$q$,$q$Skovlyst$q$,5.0,$q${"style": "Hvedeøl", "color": "Ufiltreret "}$q$::jsonb),
  ('beer',$q$Daura DAMM (Glutenfri)$q$,$q$One Pint$q$,5.4,$q${"style": "Lager", "color": "Pilsner"}$q$::jsonb),
  ('beer',$q$Wiibroe$q$,$q$Haarboe$q$,10.6,$q${"style": "Pilsner", "color": "Pilsner"}$q$::jsonb),
  ('beer',$q$Julebryg$q$,$q$Skovlyst$q$,5.5,$q${"style": "Juleøl", "color": "Mørk"}$q$::jsonb),
  ('beer',$q$Rød$q$,$q$Thisted Bryghus$q$,3.5,$q${"style": "Hvedeøl", "color": "Mat"}$q$::jsonb),
  ('beer',$q$Donker Winter Ale$q$,$q$Jacobsen$q$,8.9,$q${"style": "Juleøl", "color": "Rødbrun"}$q$::jsonb),
  ('beer',$q$Humlebryg IPA$q$,$q$Skovlyst$q$,5.5,$q${"style": "IPA", "color": "Lys"}$q$::jsonb),
  ('beer',$q$Fynsk Jul$q$,$q$Ørbæk$q$,4.9,$q${"style": "Juleøl", "color": "Lys"}$q$::jsonb),
  ('beer',$q$New York Lager$q$,$q$Nørrebro Bryghus$q$,5.2,$q${"style": "Juleøl", "color": "Lys"}$q$::jsonb),
  ('beer',$q$Dragonfruit Weissbier$q$,$q$Anarkist$q$,5.2,$q${"style": "Hvedeøl", "color": "Lys"}$q$::jsonb),
  ('beer',$q$Belgian White$q$,$q$Blue Moon$q$,5.4,$q${"style": "Hvedeøl", "color": "Lys"}$q$::jsonb),
  ('beer',$q$Rosato$q$,$q$Solveza$q$,4.5,$q${"style": "Blandingsøl", "color": "Orange"}$q$::jsonb),
  ('beer',$q$Strandløven$q$,$q$Syndikatet$q$,5.0,$q${"style": "Hvedeøl", "color": "Lys"}$q$::jsonb),
  ('beer',$q$Thyra$q$,$q$Bryggeriet Frejdahl$q$,4.6,$q${"style": "Lager", "color": "Lys"}$q$::jsonb),
  ('beer',$q$Klosterbryg$q$,$q$Århus Bryghus$q$,6.0,$q${"style": "Pilsner", "color": "Lys"}$q$::jsonb),
  ('beer',$q$Berliner Wisse$q$,$q$Anarkist$q$,4.0,$q${"style": "Sour", "color": "Appelsin"}$q$::jsonb),
  ('beer',$q$Ice cold pilsner$q$,$q$Mikkeller$q$,4.5,$q${"style": "Pilsner", "color": "Lys"}$q$::jsonb),
  ('beer',$q$Blood orange$q$,$q$Anarkist$q$,5.2,$q${"style": "Hvedeøl", "color": "Ufiltreret"}$q$::jsonb),
  ('beer',$q$Rum N'Beer$q$,$q$Thisted Bryghus$q$,9.0,$q${"style": "Hvedeøl", "color": "Dehydreret Pis"}$q$::jsonb),
  ('beer',$q$Miami Vice$q$,$q$Ugly duck brewing co.$q$,4.7,$q${"style": "IPA", "color": "Mat Pis"}$q$::jsonb),
  ('beer',$q$Lost in Space$q$,$q$Dragonfly handcraftet$q$,8.5,$q${"style": "Imperial stout", "color": "Sort"}$q$::jsonb),
  ('beer',$q$Vienna lager$q$,$q$To ØL$q$,4.7,$q${"style": "Lager", "color": "Pilsner"}$q$::jsonb),
  ('beer',$q$Morning Fresh$q$,$q$Amager Bryghus$q$,6.5,$q${"style": "Hybrid bock", "color": "Pilsner"}$q$::jsonb);

with raw(navn,maerke,anmelder,aften,score,extra,smag,duft,farve) as (values
  ($q$Guldøl (Passion)$q$,$q$Tuborg$q$,$q$Emil$q$,$q$Ukendt aften (historisk)$q$,3.5::numeric,null::numeric,$q$Frugtig$q$,$q$Citrus$q$,$q$Lys$q$),
  ($q$Guldøl (Passion)$q$,$q$Tuborg$q$,$q$Frederik$q$,$q$Ukendt aften (historisk)$q$,3.5::numeric,null::numeric,$q$Frugtig$q$,$q$Sommerlig$q$,$q$Lys$q$),
  ($q$Guldøl (Passion)$q$,$q$Tuborg$q$,$q$Søren$q$,$q$Ukendt aften (historisk)$q$,4::numeric,null::numeric,$q$Frugt$q$,$q$Mango$q$,$q$Lys$q$),
  ($q$Jule-hvidtøl$q$,$q$Ceres$q$,$q$Emil$q$,$q$Ukendt aften (historisk)$q$,3::numeric,null::numeric,$q$Ekstra Sød$q$,$q$Sød$q$,$q$Mørk$q$),
  ($q$Jule-hvidtøl$q$,$q$Ceres$q$,$q$Frederik$q$,$q$Ukendt aften (historisk)$q$,4::numeric,null::numeric,$q$Jul$q$,$q$Sød$q$,$q$Mørk$q$),
  ($q$Jule-hvidtøl$q$,$q$Ceres$q$,$q$Søren$q$,$q$Ukendt aften (historisk)$q$,3::numeric,null::numeric,$q$Slik$q$,$q$Rugbrød$q$,$q$Mørk$q$),
  ($q$Blonde$q$,$q$La Goudale$q$,$q$Emil$q$,$q$Ukendt aften (historisk)$q$,3::numeric,0.5::numeric,$q$Våd hund$q$,$q$Sød$q$,$q$Pilsner$q$),
  ($q$Blonde$q$,$q$La Goudale$q$,$q$Frederik$q$,$q$Ukendt aften (historisk)$q$,2.5::numeric,0.5::numeric,$q$Bitter$q$,$q$Let$q$,$q$Pilsner$q$),
  ($q$Blonde$q$,$q$La Goudale$q$,$q$Søren$q$,$q$Ukendt aften (historisk)$q$,2::numeric,0.5::numeric,$q$Bitter$q$,$q$Mjød$q$,$q$Pilsner$q$),
  ($q$Brown ale$q$,$q$Newcastle$q$,$q$Emil$q$,$q$Ukendt aften (historisk)$q$,2::numeric,null::numeric,$q$Vandet$q$,$q$Svag kanel$q$,$q$Karamel brun$q$),
  ($q$Brown ale$q$,$q$Newcastle$q$,$q$Frederik$q$,$q$Ukendt aften (historisk)$q$,2::numeric,null::numeric,$q$Syrlig$q$,$q$Ingeting$q$,$q$Karamel brun$q$),
  ($q$Brown ale$q$,$q$Newcastle$q$,$q$Søren$q$,$q$Ukendt aften (historisk)$q$,2::numeric,null::numeric,$q$Saftevand$q$,$q$Kanel$q$,$q$Karamel brun$q$),
  ($q$Øko Classic$q$,$q$Gram Slot$q$,$q$Emil$q$,$q$Ukendt aften (historisk)$q$,3::numeric,null::numeric,$q$Pilsner$q$,$q$Gæret$q$,$q$Pilsner$q$),
  ($q$Øko Classic$q$,$q$Gram Slot$q$,$q$Frederik$q$,$q$Ukendt aften (historisk)$q$,3::numeric,null::numeric,$q$Pilsner$q$,$q$Mild$q$,$q$Pilsner$q$),
  ($q$Øko Classic$q$,$q$Gram Slot$q$,$q$Søren$q$,$q$Ukendt aften (historisk)$q$,3::numeric,null::numeric,$q$Svag citrus$q$,$q$Vand$q$,$q$Pilsner$q$),
  ($q$Brown$q$,$q$Thisted Bryghus$q$,$q$Emil$q$,$q$Ukendt aften (historisk)$q$,4::numeric,null::numeric,$q$Bittersød$q$,$q$Rugbrød$q$,$q$Te$q$),
  ($q$Brown$q$,$q$Thisted Bryghus$q$,$q$Frederik$q$,$q$Ukendt aften (historisk)$q$,2::numeric,null::numeric,$q$Røget$q$,$q$Rugbrød$q$,$q$Te$q$),
  ($q$Brown$q$,$q$Thisted Bryghus$q$,$q$Søren$q$,$q$Ukendt aften (historisk)$q$,3.5::numeric,null::numeric,$q$Kaffe$q$,$q$Honning$q$,$q$Te$q$),
  ($q$Velvet Galaxy$q$,$q$Jacobsen$q$,$q$Emil$q$,$q$Ukendt aften (historisk)$q$,4::numeric,null::numeric,$q$Honning$q$,$q$Sød$q$,$q$Honning$q$),
  ($q$Velvet Galaxy$q$,$q$Jacobsen$q$,$q$Frederik$q$,$q$Ukendt aften (historisk)$q$,4::numeric,null::numeric,$q$Bær$q$,$q$Bitter$q$,$q$Honning$q$),
  ($q$Velvet Galaxy$q$,$q$Jacobsen$q$,$q$Søren$q$,$q$Ukendt aften (historisk)$q$,3.5::numeric,null::numeric,$q$Desperados$q$,$q$Blomst$q$,$q$Honning$q$),
  ($q$Limfjords Porter$q$,$q$Thisted Bryghus$q$,$q$Emil$q$,$q$Ukendt aften (historisk)$q$,3.5::numeric,0.5::numeric,$q$Mørk Chokolade$q$,$q$Isle Whiskey$q$,$q$Kul$q$),
  ($q$Limfjords Porter$q$,$q$Thisted Bryghus$q$,$q$Frederik$q$,$q$Ukendt aften (historisk)$q$,2::numeric,0.5::numeric,$q$Røget$q$,$q$Tjære$q$,$q$Kul$q$),
  ($q$Limfjords Porter$q$,$q$Thisted Bryghus$q$,$q$Søren$q$,$q$Ukendt aften (historisk)$q$,3.5::numeric,0.5::numeric,$q$Bål$q$,$q$Bål$q$,$q$Kul$q$),
  ($q$Glutenfri Øko Julebryg$q$,$q$Svaneke$q$,$q$Emil$q$,$q$Ukendt aften (historisk)$q$,3.5::numeric,null::numeric,$q$Espresso$q$,$q$Honning$q$,$q$Kaffe$q$),
  ($q$Glutenfri Øko Julebryg$q$,$q$Svaneke$q$,$q$Frederik$q$,$q$Ukendt aften (historisk)$q$,2.5::numeric,null::numeric,$q$Mørk$q$,$q$Egefad$q$,$q$Kaffe$q$),
  ($q$Glutenfri Øko Julebryg$q$,$q$Svaneke$q$,$q$Søren$q$,$q$Ukendt aften (historisk)$q$,3.5::numeric,null::numeric,$q$Krydret$q$,$q$Honning$q$,$q$Kaffe$q$),
  ($q$Czech Lager$q$,$q$Budějovický Budvar$q$,$q$Emil$q$,$q$Ukendt aften (historisk)$q$,3::numeric,null::numeric,$q$Kedelig$q$,$q$Vandet$q$,$q$Gylden$q$),
  ($q$Czech Lager$q$,$q$Budějovický Budvar$q$,$q$Frederik$q$,$q$Ukendt aften (historisk)$q$,2.5::numeric,null::numeric,$q$Svag syrlig$q$,$q$Pis$q$,$q$Gylden$q$),
  ($q$Czech Lager$q$,$q$Budějovický Budvar$q$,$q$Søren$q$,$q$Ukendt aften (historisk)$q$,2::numeric,null::numeric,$q$Heiniken$q$,$q$Pilsner$q$,$q$Gylden$q$),
  ($q$Blå Thor$q$,$q$Thor$q$,$q$Emil$q$,$q$Ukendt aften (historisk)$q$,3::numeric,null::numeric,$q$Syre$q$,$q$Syre$q$,$q$Gul$q$),
  ($q$Blå Thor$q$,$q$Thor$q$,$q$Frederik$q$,$q$Ukendt aften (historisk)$q$,3::numeric,null::numeric,$q$Sur Fisse$q$,$q$Citrus$q$,$q$Gul$q$),
  ($q$Blå Thor$q$,$q$Thor$q$,$q$Søren$q$,$q$Ukendt aften (historisk)$q$,3::numeric,null::numeric,$q$Øl$q$,$q$Appelsin$q$,$q$Gul$q$),
  ($q$Weissbier$q$,$q$Paulaner München$q$,$q$Emil$q$,$q$Ukendt aften (historisk)$q$,4::numeric,null::numeric,$q$Jungle$q$,$q$Banan$q$,$q$Mat Pis$q$),
  ($q$Weissbier$q$,$q$Paulaner München$q$,$q$Frederik$q$,$q$Ukendt aften (historisk)$q$,3::numeric,null::numeric,$q$Sød Pilsner$q$,$q$Frugtig$q$,$q$Mat Pis$q$),
  ($q$Weissbier$q$,$q$Paulaner München$q$,$q$Søren$q$,$q$Ukendt aften (historisk)$q$,3.5::numeric,null::numeric,$q$Smøg$q$,$q$Røg$q$,$q$Mat Pis$q$),
  ($q$HC Andersen$q$,$q$Albani$q$,$q$Emil$q$,$q$Ukendt aften (historisk)$q$,3.5::numeric,0.5::numeric,$q$Banan$q$,$q$Syrlig$q$,$q$Honning$q$),
  ($q$HC Andersen$q$,$q$Albani$q$,$q$Frederik$q$,$q$Ukendt aften (historisk)$q$,3.5::numeric,0.5::numeric,$q$Sødlig$q$,$q$Piller$q$,$q$Honning$q$),
  ($q$HC Andersen$q$,$q$Albani$q$,$q$Søren$q$,$q$Ukendt aften (historisk)$q$,3.5::numeric,0.5::numeric,$q$Røget pils$q$,$q$Farmors Fisse$q$,$q$Honning$q$),
  ($q$Double Ambrée$q$,$q$Grimbergen$q$,$q$Emil$q$,$q$Ukendt aften (historisk)$q$,3::numeric,null::numeric,$q$Karamel$q$,$q$Karamel$q$,$q$Rav$q$),
  ($q$Double Ambrée$q$,$q$Grimbergen$q$,$q$Frederik$q$,$q$Ukendt aften (historisk)$q$,3::numeric,null::numeric,$q$Brændt$q$,$q$Røget$q$,$q$Rav$q$),
  ($q$St. Omer$q$,$q$Brasserie Francaise$q$,$q$Emil$q$,$q$Ukendt aften (historisk)$q$,2::numeric,0.5::numeric,$q$Halvbitter pilsner$q$,$q$DP$q$,$q$Død pilsner$q$),
  ($q$St. Omer$q$,$q$Brasserie Francaise$q$,$q$Frederik$q$,$q$Ukendt aften (historisk)$q$,2::numeric,0.5::numeric,$q$Bitter pilsner$q$,$q$Fesent$q$,$q$Gylden$q$),
  ($q$St. Omer$q$,$q$Brasserie Francaise$q$,$q$Søren$q$,$q$Ukendt aften (historisk)$q$,3::numeric,0.5::numeric,$q$Let$q$,$q$Havduft$q$,$q$Tynd guld$q$),
  ($q$Biére Blonde Légére$q$,$q$Goudale$q$,$q$Emil$q$,$q$Ukendt aften (historisk)$q$,3.5::numeric,null::numeric,$q$Bittersødlig$q$,$q$Malt$q$,$q$Ufiltreret$q$),
  ($q$Biére Blonde Légére$q$,$q$Goudale$q$,$q$Frederik$q$,$q$Ukendt aften (historisk)$q$,3.5::numeric,null::numeric,$q$Sommerlig$q$,$q$Sødlig$q$,$q$Ufiltreret$q$),
  ($q$Biére Blonde Légére$q$,$q$Goudale$q$,$q$Søren$q$,$q$Ukendt aften (historisk)$q$,3.5::numeric,null::numeric,$q$Letsommer$q$,$q$Honning$q$,$q$Ufiltreret$q$),
  ($q$Imperial Stout$q$,$q$Stem Brew$q$,$q$Emil$q$,$q$Ukendt aften (historisk)$q$,3.5::numeric,0.5::numeric,$q$Kaffe$q$,$q$Mørk chokolade$q$,$q$Sort$q$),
  ($q$Imperial Stout$q$,$q$Stem Brew$q$,$q$Frederik$q$,$q$Ukendt aften (historisk)$q$,3::numeric,0.5::numeric,$q$Mørk sødme$q$,$q$Rustikt$q$,$q$Sort$q$),
  ($q$Imperial Stout$q$,$q$Stem Brew$q$,$q$Søren$q$,$q$Ukendt aften (historisk)$q$,3::numeric,0.5::numeric,$q$Tynd kaffe$q$,$q$Havsalt$q$,$q$Sort$q$),
  ($q$Top pilsner$q$,$q$Ceres$q$,$q$Emil$q$,$q$Ukendt aften (historisk)$q$,3::numeric,null::numeric,$q$Pilsner$q$,$q$Pilsner$q$,$q$Pilsner$q$),
  ($q$Top pilsner$q$,$q$Ceres$q$,$q$Frederik$q$,$q$Ukendt aften (historisk)$q$,2.5::numeric,null::numeric,$q$Tynd$q$,$q$Pilsner$q$,$q$Pilsner$q$),
  ($q$Top pilsner$q$,$q$Ceres$q$,$q$Søren$q$,$q$Ukendt aften (historisk)$q$,2.5::numeric,null::numeric,$q$Nullermand$q$,$q$Pilsner$q$,$q$Pilsner$q$),
  ($q$Didrik$q$,$q$De 5 gaarde$q$,$q$Emil$q$,$q$Ukendt aften (historisk)$q$,2.5::numeric,0.5::numeric,$q$Sød$q$,$q$Sur/sød$q$,$q$Klassisk$q$),
  ($q$Didrik$q$,$q$De 5 gaarde$q$,$q$Frederik$q$,$q$Ukendt aften (historisk)$q$,2.5::numeric,0.5::numeric,$q$Fyldig$q$,$q$Metalisk$q$,$q$Klassisk$q$),
  ($q$Didrik$q$,$q$De 5 gaarde$q$,$q$Søren$q$,$q$Ukendt aften (historisk)$q$,3.5::numeric,0.5::numeric,$q$Metalisk$q$,$q$Blomstermark$q$,$q$Klassisk$q$),
  ($q$?$q$,$q$?$q$,$q$Emil$q$,$q$Ukendt aften (historisk)$q$,2.5::numeric,null::numeric,$q$Våd hund$q$,$q$Desperado$q$,$q$Mat lys$q$),
  ($q$?$q$,$q$?$q$,$q$Frederik$q$,$q$Ukendt aften (historisk)$q$,3.5::numeric,null::numeric,$q$Sommer$q$,$q$Citrus desperado$q$,$q$Mat lys$q$),
  ($q$?$q$,$q$?$q$,$q$Søren$q$,$q$Ukendt aften (historisk)$q$,3::numeric,null::numeric,$q$Citrus rengøringsmiddel$q$,$q$Lime desperados$q$,$q$Mat lys$q$),
  ($q$Ufiltreret mango IPA$q$,$q$Schiøtz$q$,$q$Emil$q$,$q$Ukendt aften (historisk)$q$,3.5::numeric,null::numeric,$q$Bitter banan$q$,$q$Mango$q$,$q$Ufiltreret$q$),
  ($q$Ufiltreret mango IPA$q$,$q$Schiøtz$q$,$q$Frederik$q$,$q$Ukendt aften (historisk)$q$,1.5::numeric,null::numeric,$q$Frugtig bitter$q$,$q$Frugtig$q$,$q$Ufiltreret$q$),
  ($q$Ufiltreret mango IPA$q$,$q$Schiøtz$q$,$q$Søren$q$,$q$Ukendt aften (historisk)$q$,4::numeric,null::numeric,$q$Bitter mango$q$,$q$Mango$q$,$q$Ufiltreret$q$),
  ($q$Dunkel$q$,$q$Erdinger$q$,$q$Emil$q$,$q$Ukendt aften (historisk)$q$,3::numeric,null::numeric,$q$Chokolade$q$,$q$Krads$q$,$q$Sort$q$),
  ($q$Dunkel$q$,$q$Erdinger$q$,$q$Frederik$q$,$q$Ukendt aften (historisk)$q$,2.5::numeric,null::numeric,$q$Ristet$q$,$q$Pilsner$q$,$q$Sort$q$),
  ($q$Dunkel$q$,$q$Erdinger$q$,$q$Søren$q$,$q$Ukendt aften (historisk)$q$,3.5::numeric,null::numeric,$q$Skum$q$,$q$Lys$q$,$q$Sort$q$),
  ($q$GB Jul$q$,$q$Gourmet Bryggeriet$q$,$q$Emil$q$,$q$Ukendt aften (historisk)$q$,1::numeric,0.5::numeric,$q$Lakrids$q$,$q$Sød$q$,$q$Cola$q$),
  ($q$GB Jul$q$,$q$Gourmet Bryggeriet$q$,$q$Frederik$q$,$q$Ukendt aften (historisk)$q$,1::numeric,0.5::numeric,$q$Eksplosion af dårlig$q$,$q$Sød$q$,$q$Cola$q$),
  ($q$GB Jul$q$,$q$Gourmet Bryggeriet$q$,$q$Søren$q$,$q$Ukendt aften (historisk)$q$,3::numeric,0.5::numeric,$q$Vådt rugbrød$q$,$q$Sød$q$,$q$Cola$q$),
  ($q$Blanche$q$,$q$Skovlyst$q$,$q$Emil$q$,$q$Ukendt aften (historisk)$q$,3::numeric,null::numeric,$q$Flad desparados$q$,$q$Banan$q$,$q$Ufiltreret $q$),
  ($q$Blanche$q$,$q$Skovlyst$q$,$q$Frederik$q$,$q$Ukendt aften (historisk)$q$,2.5::numeric,null::numeric,$q$Flad desparados$q$,$q$Banan$q$,$q$Ufiltreret $q$),
  ($q$Blanche$q$,$q$Skovlyst$q$,$q$Søren$q$,$q$Ukendt aften (historisk)$q$,3::numeric,null::numeric,$q$Kraftig$q$,$q$Citrus$q$,$q$Ufiltreret $q$),
  ($q$Daura DAMM (Glutenfri)$q$,$q$One Pint$q$,$q$Emil$q$,$q$Ukendt aften (historisk)$q$,2::numeric,null::numeric,$q$Bitter$q$,$q$Våd hund$q$,$q$Pilsner$q$),
  ($q$Daura DAMM (Glutenfri)$q$,$q$One Pint$q$,$q$Frederik$q$,$q$Ukendt aften (historisk)$q$,2::numeric,null::numeric,$q$Pilsner$q$,$q$Pilsner$q$,$q$Pilsner$q$),
  ($q$Daura DAMM (Glutenfri)$q$,$q$One Pint$q$,$q$Søren$q$,$q$Ukendt aften (historisk)$q$,1::numeric,null::numeric,$q$Ingenting$q$,$q$Ingenting$q$,$q$Pilsner$q$),
  ($q$Wiibroe$q$,$q$Haarboe$q$,$q$Emil$q$,$q$Aften hos Frederik$q$,1.5::numeric,1.0::numeric,$q$Billig Habroe$q$,$q$Harboe$q$,$q$Pilsner$q$),
  ($q$Wiibroe$q$,$q$Haarboe$q$,$q$Frederik$q$,$q$Aften hos Frederik$q$,1::numeric,1::numeric,$q$Smagen af grim$q$,$q$Ingenting$q$,$q$Pilsner$q$),
  ($q$Wiibroe$q$,$q$Haarboe$q$,$q$Søren$q$,$q$Aften hos Frederik$q$,1.5::numeric,1.0::numeric,$q$Harbo$q$,$q$Sød Harboe$q$,$q$Pilsner$q$),
  ($q$Julebryg$q$,$q$Skovlyst$q$,$q$Emil$q$,$q$Aften hos Frederik$q$,3::numeric,null::numeric,$q$Kanel$q$,$q$Kanel$q$,$q$Mørk$q$),
  ($q$Julebryg$q$,$q$Skovlyst$q$,$q$Frederik$q$,$q$Aften hos Frederik$q$,3::numeric,null::numeric,$q$Kanel$q$,$q$Sødt kryderri$q$,$q$Mørk$q$),
  ($q$Julebryg$q$,$q$Skovlyst$q$,$q$Søren$q$,$q$Aften hos Frederik$q$,3::numeric,null::numeric,$q$Kanelsnegl$q$,$q$Pesto$q$,$q$Mørk$q$),
  ($q$Rød$q$,$q$Thisted Bryghus$q$,$q$Emil$q$,$q$Aften hos Frederik$q$,3::numeric,null::numeric,$q$Lidt sød$q$,$q$Bitter$q$,$q$Mat$q$),
  ($q$Rød$q$,$q$Thisted Bryghus$q$,$q$Frederik$q$,$q$Aften hos Frederik$q$,3::numeric,null::numeric,$q$Frisk$q$,$q$Ingenting$q$,$q$Mat$q$),
  ($q$Rød$q$,$q$Thisted Bryghus$q$,$q$Søren$q$,$q$Aften hos Frederik$q$,2.5::numeric,null::numeric,$q$Ikke så meget$q$,$q$IPA$q$,$q$Mat$q$),
  ($q$Donker Winter Ale$q$,$q$Jacobsen$q$,$q$Emil$q$,$q$Aften hos Frederik$q$,2::numeric,0.5::numeric,$q$Kvalm$q$,$q$Sød$q$,$q$Rødbrun$q$),
  ($q$Donker Winter Ale$q$,$q$Jacobsen$q$,$q$Frederik$q$,$q$Aften hos Frederik$q$,1::numeric,0.5::numeric,$q$Grim$q$,$q$Metal$q$,$q$Rødbrun$q$),
  ($q$Donker Winter Ale$q$,$q$Jacobsen$q$,$q$Søren$q$,$q$Aften hos Frederik$q$,1.5::numeric,0.5::numeric,$q$Stor næse$q$,$q$Beerspa$q$,$q$Rødbrun$q$),
  ($q$Humlebryg IPA$q$,$q$Skovlyst$q$,$q$Søren$q$,$q$Aften hos Frederik$q$,3.5::numeric,null::numeric,$q$Bitter lækkerhed$q$,$q$Citrus og blomster$q$,$q$Lys$q$),
  ($q$Humlebryg IPA$q$,$q$Skovlyst$q$,$q$Emil$q$,$q$Aften hos Frederik$q$,3.5::numeric,null::numeric,$q$Bitter lækker$q$,$q$Godhed$q$,$q$Lys$q$),
  ($q$Humlebryg IPA$q$,$q$Skovlyst$q$,$q$Frederik$q$,$q$Aften hos Frederik$q$,0::numeric,null::numeric,$q$Bitter lækker$q$,$q$Godhed$q$,$q$Lys$q$),
  ($q$Fynsk Jul$q$,$q$Ørbæk$q$,$q$Frederik$q$,$q$Aften hos Frederik$q$,3::numeric,null::numeric,$q$Let smag$q$,$q$Frisk$q$,$q$Lys$q$),
  ($q$Fynsk Jul$q$,$q$Ørbæk$q$,$q$Søren$q$,$q$Aften hos Frederik$q$,1.5::numeric,null::numeric,$q$Tynd saft$q$,$q$Hyldeblomst$q$,$q$Lys$q$),
  ($q$Fynsk Jul$q$,$q$Ørbæk$q$,$q$Emil$q$,$q$Aften hos Frederik$q$,1::numeric,null::numeric,$q$Flad Ceres Top$q$,$q$Hyldeblomst$q$,$q$Lys$q$),
  ($q$New York Lager$q$,$q$Nørrebro Bryghus$q$,$q$Frederik$q$,$q$Aften hos Frederik$q$,1::numeric,null::numeric,$q$Bitter$q$,$q$Flad Øl$q$,$q$Lys$q$),
  ($q$New York Lager$q$,$q$Nørrebro Bryghus$q$,$q$Søren$q$,$q$Aften hos Frederik$q$,2::numeric,null::numeric,$q$Øl Spa$q$,$q$Appelsin$q$,$q$Lys$q$),
  ($q$New York Lager$q$,$q$Nørrebro Bryghus$q$,$q$Emil$q$,$q$Aften hos Frederik$q$,2.5::numeric,null::numeric,$q$Våd hund$q$,$q$OpvaskeVand$q$,$q$Lys$q$),
  ($q$Dragonfruit Weissbier$q$,$q$Anarkist$q$,$q$Frederik$q$,$q$Aften hos Frederik$q$,3::numeric,null::numeric,$q$Frugtig$q$,$q$Nye muligheder$q$,$q$Lys$q$),
  ($q$Dragonfruit Weissbier$q$,$q$Anarkist$q$,$q$Søren$q$,$q$Aften hos Frederik$q$,2::numeric,null::numeric,$q$Tynd frugt$q$,$q$Grøn slik$q$,$q$Lys$q$),
  ($q$Dragonfruit Weissbier$q$,$q$Anarkist$q$,$q$Emil$q$,$q$Aften hos Frederik$q$,3::numeric,null::numeric,$q$Juice$q$,$q$Sødhed$q$,$q$Lys$q$),
  ($q$Belgian White$q$,$q$Blue Moon$q$,$q$Frederik$q$,$q$Julefrokost hos Emil$q$,2::numeric,null::numeric,$q$OpvaskeMiddel$q$,$q$Sæbe$q$,$q$Lys$q$),
  ($q$Belgian White$q$,$q$Blue Moon$q$,$q$Søren$q$,$q$Julefrokost hos Emil$q$,1::numeric,null::numeric,$q$OpvaskeMiddel$q$,$q$Sød Sæbe$q$,$q$Lys$q$),
  ($q$Belgian White$q$,$q$Blue Moon$q$,$q$Emil$q$,$q$Julefrokost hos Emil$q$,1::numeric,null::numeric,$q$Korriander$q$,$q$Sæbe$q$,$q$Lys$q$),
  ($q$Rosato$q$,$q$Solveza$q$,$q$Frederik$q$,$q$Julefrokost hos Emil$q$,2.5::numeric,null::numeric,$q$Syntetisk slik$q$,$q$Tyggegummi$q$,$q$Orange$q$),
  ($q$Rosato$q$,$q$Solveza$q$,$q$Søren$q$,$q$Julefrokost hos Emil$q$,3.5::numeric,null::numeric,$q$Bubble gum$q$,$q$Bubblegum$q$,$q$Orange$q$),
  ($q$Rosato$q$,$q$Solveza$q$,$q$Emil$q$,$q$Julefrokost hos Emil$q$,2::numeric,null::numeric,$q$Slik (Medium godt slik)$q$,$q$Slik$q$,$q$Orange$q$),
  ($q$Strandløven$q$,$q$Syndikatet$q$,$q$Frederik$q$,$q$Julefrokost hos Emil$q$,2::numeric,null::numeric,$q$Syrlig$q$,$q$IPA-ish$q$,$q$Lys$q$),
  ($q$Strandløven$q$,$q$Syndikatet$q$,$q$Søren$q$,$q$Julefrokost hos Emil$q$,3::numeric,null::numeric,$q$Saltvand$q$,$q$Tang$q$,$q$Lys$q$),
  ($q$Strandløven$q$,$q$Syndikatet$q$,$q$Emil$q$,$q$Julefrokost hos Emil$q$,4::numeric,null::numeric,$q$Sommerlækkerier$q$,$q$Citrus$q$,$q$Lys$q$),
  ($q$Thyra$q$,$q$Bryggeriet Frejdahl$q$,$q$Frederik$q$,$q$Julefrokost hos Emil$q$,3.5::numeric,null::numeric,$q$Smagfuld$q$,$q$Honning$q$,$q$Lys$q$),
  ($q$Thyra$q$,$q$Bryggeriet Frejdahl$q$,$q$Søren$q$,$q$Julefrokost hos Emil$q$,2::numeric,null::numeric,$q$Honning$q$,$q$Carlsberg$q$,$q$Lys$q$),
  ($q$Thyra$q$,$q$Bryggeriet Frejdahl$q$,$q$Emil$q$,$q$Julefrokost hos Emil$q$,2.5::numeric,null::numeric,$q$Sød vinter$q$,$q$Sød urin$q$,$q$Lys$q$),
  ($q$Klosterbryg$q$,$q$Århus Bryghus$q$,$q$Frederik$q$,$q$Julefrokost hos Emil$q$,2.5::numeric,null::numeric,$q$PowerFULL$q$,$q$Kornmark$q$,$q$Lys$q$),
  ($q$Klosterbryg$q$,$q$Århus Bryghus$q$,$q$Søren$q$,$q$Julefrokost hos Emil$q$,2.5::numeric,null::numeric,$q$WEAK$q$,$q$Æble$q$,$q$Lys$q$),
  ($q$Klosterbryg$q$,$q$Århus Bryghus$q$,$q$Emil$q$,$q$Julefrokost hos Emil$q$,1::numeric,null::numeric,$q$Hader smagen$q$,$q$Frøderen$q$,$q$Lys$q$),
  ($q$Berliner Wisse$q$,$q$Anarkist$q$,$q$Frederik$q$,$q$Julefrokost hos Emil$q$,3.5::numeric,null::numeric,$q$Multi Juice$q$,$q$Frugt Punch$q$,$q$Appelsin$q$),
  ($q$Berliner Wisse$q$,$q$Anarkist$q$,$q$Søren$q$,$q$Julefrokost hos Emil$q$,4::numeric,null::numeric,$q$Sour Is$q$,$q$Mango$q$,$q$Appelsin$q$),
  ($q$Berliner Wisse$q$,$q$Anarkist$q$,$q$Emil$q$,$q$Julefrokost hos Emil$q$,4::numeric,null::numeric,$q$Multi Juice$q$,$q$Juice$q$,$q$Appelsin$q$),
  ($q$Ice cold pilsner$q$,$q$Mikkeller$q$,$q$Frederik$q$,$q$Julefrokost hos Emil$q$,2::numeric,null::numeric,$q$Lidt bitter lidt frugtig$q$,$q$Lige til at lukke op og bide i$q$,$q$Lys$q$),
  ($q$Ice cold pilsner$q$,$q$Mikkeller$q$,$q$Søren$q$,$q$Julefrokost hos Emil$q$,3::numeric,null::numeric,$q$Cirtus$q$,$q$IPA$q$,$q$Lys$q$),
  ($q$Ice cold pilsner$q$,$q$Mikkeller$q$,$q$Emil$q$,$q$Julefrokost hos Emil$q$,4::numeric,null::numeric,$q$Bitter banan$q$,$q$Lækker$q$,$q$Lys$q$),
  ($q$Blood orange$q$,$q$Anarkist$q$,$q$Frederik$q$,$q$Julefrokost hos Emil$q$,3::numeric,null::numeric,$q$Frugtig$q$,$q$IPA$q$,$q$Ufiltreret$q$),
  ($q$Blood orange$q$,$q$Anarkist$q$,$q$Søren$q$,$q$Julefrokost hos Emil$q$,4.5::numeric,null::numeric,$q$Playboy$q$,$q$Æble fisse$q$,$q$Ufiltreret$q$),
  ($q$Blood orange$q$,$q$Anarkist$q$,$q$Emil$q$,$q$Julefrokost hos Emil$q$,4::numeric,null::numeric,$q$Fråd$q$,$q$Multijuice$q$,$q$Ufiltreret$q$),
  ($q$Rum N'Beer$q$,$q$Thisted Bryghus$q$,$q$Frederik$q$,$q$Hillerød$q$,1.5::numeric,0.5::numeric,$q$grimt og bittert$q$,$q$Sødlig$q$,$q$Dehydreret Pis$q$),
  ($q$Rum N'Beer$q$,$q$Thisted Bryghus$q$,$q$Søren$q$,$q$Hillerød$q$,1.5::numeric,0.5::numeric,$q$Bitter$q$,$q$Sød$q$,$q$Dehydreret Pis$q$),
  ($q$Rum N'Beer$q$,$q$Thisted Bryghus$q$,$q$Emil$q$,$q$Hillerød$q$,1::numeric,0.5::numeric,$q$Bitter Pis$q$,$q$Sød urin$q$,$q$Rav$q$),
  ($q$Miami Vice$q$,$q$Ugly duck brewing co.$q$,$q$Frederik$q$,$q$Hillerød$q$,2::numeric,null::numeric,$q$Mild IPA$q$,$q$Mild IPA$q$,$q$Mat Pis$q$),
  ($q$Miami Vice$q$,$q$Ugly duck brewing co.$q$,$q$Søren$q$,$q$Hillerød$q$,3::numeric,null::numeric,$q$Meget Mild$q$,$q$Frugt$q$,$q$Toget$q$),
  ($q$Miami Vice$q$,$q$Ugly duck brewing co.$q$,$q$Emil$q$,$q$Hillerød$q$,3.5::numeric,null::numeric,$q$Frugty bitter$q$,$q$Bitter$q$,$q$Mat pis$q$),
  ($q$Lost in Space$q$,$q$Dragonfly handcraftet$q$,$q$Frederik$q$,$q$Hillerød$q$,2::numeric,0.5::numeric,$q$Brandt snobrød$q$,$q$Stout$q$,$q$Sort$q$),
  ($q$Lost in Space$q$,$q$Dragonfly handcraftet$q$,$q$Søren$q$,$q$Hillerød$q$,3::numeric,0.5::numeric,$q$Let for dens farve$q$,$q$Stout$q$,$q$Sort$q$),
  ($q$Lost in Space$q$,$q$Dragonfly handcraftet$q$,$q$Emil$q$,$q$Hillerød$q$,2::numeric,0.5::numeric,$q$Bitter kaffe lort$q$,$q$Sød kaffe$q$,$q$Mørk Lort$q$),
  ($q$Vienna lager$q$,$q$To ØL$q$,$q$Frederik$q$,$q$Hillerød$q$,3.2::numeric,null::numeric,$q$Mild$q$,$q$Sødlig$q$,$q$Pilsner$q$),
  ($q$Vienna lager$q$,$q$To ØL$q$,$q$Søren$q$,$q$Hillerød$q$,2.9::numeric,null::numeric,$q$Lidt bitter$q$,$q$Sød IPA$q$,$q$Pilsner$q$),
  ($q$Vienna lager$q$,$q$To ØL$q$,$q$Emil$q$,$q$Hillerød$q$,4.1::numeric,null::numeric,$q$God$q$,$q$Sødhed$q$,$q$Pilsner$q$),
  ($q$Morning Fresh$q$,$q$Amager Bryghus$q$,$q$Frederik$q$,$q$Hillerød$q$,2.2::numeric,null::numeric,$q$Bitter$q$,$q$Svag$q$,$q$Pilsner$q$),
  ($q$Morning Fresh$q$,$q$Amager Bryghus$q$,$q$Søren$q$,$q$Hillerød$q$,3.7::numeric,null::numeric,$q$Morgenbajer$q$,$q$Normal øl$q$,$q$Lys øl$q$),
  ($q$Morning Fresh$q$,$q$Amager Bryghus$q$,$q$Emil$q$,$q$Hillerød$q$,3.715::numeric,null::numeric,$q$Pilsner (pilsner) ikke på mig - jeg jeg jeg ville have de på stilarten. Nu skriver han alt, hvad jeg siger.$q$,$q$Ingenting$q$,$q$Pilsner$q$)
)
insert into ratings (product_id,taster_id,session_id,score,extra_points,taste_note,aroma_note,color_note)
select p.id,t.id,s.id,raw.score,raw.extra,raw.smag,raw.duft,raw.farve
from raw
join products p on p.category_id='beer' and p.name=raw.navn and p.producer is not distinct from raw.maerke
join tasters t on t.name=raw.anmelder
join sessions s on s.category_id='beer' and s.name=raw.aften
on conflict (product_id,taster_id) do nothing;